apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: sklearn
spec:
  name: cardPrices
  predictors:
  - graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: https://dissertationfco.blob.core.windows.net/dissfco/model.joblib
      name: classifier
    name: default
    replicas: 1